version: '3'

services:
  oncall-web:
    build: .
    pull_policy: build
    hostname: oncall
    ports:
      - "8080:8080"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
    volumes:
      - ./configs/config.docker.yaml:/oncall/_data/home/oncall/config/config.yaml
      - oncall:/_data
    networks:
      - default

  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:5.7
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - default
      
volumes:
  oncall:
    external: true
