version: '3'

services:
  oncall-web:
    build: .
    pull_policy: build
    hostname: oncall
    ports:
      - "8080:8080"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml

  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234

networks: 
    default: 
      name: bridge
      external: true
      network_mode: 'bridge'
