version: '3'

services:
  oncall-web:
    build: .
    pull_policy: build
    hostname: oncall
    depends_on:
      - oncall-mysql
    ports:
      - "8080:8080"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/configs/config.yaml
      - oncall:/_data
    networks:
      - default

  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - default
      
volumes:
  oncall:
    external: true
